name: Check if version exist on docker registry
on:
  pull_request:
    branches:
      - "master"
jobs:
  version-check-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tools
        run: apt install jq -y          
      - name: Get version
        run: BASEDIR=$(pwd) ./tools/get_version.sh
      - name: Set version
        run: BASEDIR=$(pwd) ./tools/get_version.sh >> $GITHUB_ENV
      - name: Check if tag exist 2
        run: |
          TAG=$(git tag -l ${{ env.VERSION }})
          if [ -n "$TAG" ]
          then
            echo "::error::This site version tag ($TAG) already exists in repository."
            exit 1
          fi 

  version-check-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tools
        run: apt install jq -y          
      - name: Get version
        run: BASEDIR=$(pwd) ./tools/get_version.sh
      - name: Set version
        run: BASEDIR=$(pwd) ./tools/get_version.sh >> $GITHUB_ENV
      - name: Check site current version
        id: is_image_exist
        uses: tm-bverret/docker-exist-action@v1.1.2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: omicsdatascience/omicsdatascience-site:${{ env.VERSION }}
      - name: evaluation result?
        run: |
          echo "Result of image check was: ${{ env.RESULT }}" 
        env:
          RESULT: ${{ steps.is_image_exist.outputs.image_exist }}          
      - name: multimomix current version docker image exists?
        if: steps.is_image_exist.outputs.image_exist == 1
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This site version already exists on docker registry')